In [47]:
#numpy.lesson2 多維陣列ndarray基礎
#載入numpy套件
import numpy as np

#建立一維陣列
data=np.array([3, 2, 6, 4])
print(data)
data=np.empty(4) #創造一個有四個資料的一維陣列，資料未指定
print(data)
data=np.zeros(3)
print(data)
data=np.ones(3)
print(data)
data=np.arange(8)
print(data)
print("----------")

#建立二維陣列
data=np.array([ #創造一個3*3的二維陣列
    [2, 3, 2],
    [1, 5, 2],
    [4, 2, 1]
])
print(data)
data=np.empty([3, 3]) #創造一個3*3的二維陣列, 資料未指定(如果出現某些特定數字，只是剛剛好)
print(data)
data=np.ones([2, 3]) #創造一個2*3的二維陣列，資料都是1
print(data)
print("----------")

#建立三維陣列
data=np.array([ #根據列表創造一個2*2*2的三維陣列
    [
        [3, 1],[1, 2]
    ],
    [
        [2, 5],[10, 2]
    ]
])
print(data)
data=np.zeros([3, 1, 3]) #創造一個3*1*3的三維陣列，資料都是0
print(data)
print("----------")

#建立高維陣列
data=np.array([ #創造一個1*1*2*3的四維資料
    [
        [
            [3, 2, 1],
            [5, 5, 10]
        ]
    ]
])
print(data)
data=np.ones([2, 1, 1, 2]) #創造一個2*1*1*2的四維陣列，資料都是1
print(data)

[3 2 6 4]
[1. 1. 1. 1.]
[0. 0. 0.]
[1. 1. 1.]
[0 1 2 3 4 5 6 7]
----------
[[2 3 2]
 [1 5 2]
 [4 2 1]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
----------
[[[ 3  1]
  [ 1  2]]

 [[ 2  5]
  [10  2]]]
[[[0. 0. 0.]]

 [[0. 0. 0.]]

 [[0. 0. 0.]]]
----------
[[[[ 3  2  1]
   [ 5  5 10]]]]
[[[[1. 1.]]]


 [[[1. 1.]]]]


In [7]:
#numpy.lesson3 多維陣列ndarray基礎運算功能
#載入numpy套件
import numpy as np

#逐元運算(elementwise) (兩個多元陣列應有相同shape)
data1=np.array([3, 2, 10])
data2=np.array([1, 3, 6])
result=data1+data2
print("加法", result)
result=data1*data2
print("乘法", result)
result=data1>data2
print("大於", result)
result=data1==data2
print("是否相等", result)
print("----------")

#矩陣運算(matrix)
data1=np.array([
    [1, 3]
]) #1*2
data2=np.array([
    [2, -1, 3],
    [-2, 4, 1]
]) #2*3
result=data1.dot(data2) #1*3 #result=data1@data2(結果相同，換個寫法)
print("內積", result)
result=np.outer(data1, data2) #2*6
print("外積", result)
#內積 兩個矩陣中間的數字沒對上就沒辦法做內積 ex:(1*3)(2*3)
print("----------")

#統計運算(statistics)
data=np.array([
    [2, 1, 7],
    [-5, 3, 8]
]) #2*3
result=data.sum()
print("總和", result)
result=data.max()
print("最大值", result)
result=data.mean()
print("平均數", result)
result=data.std()
print("標準差", result)
print("----------")
result=data.sum(axis=0) #針對欄做總和column(針對第一個維度做總和)
print(result)
result=data.sum(axis=1) #針對列做總和row(針對第二個維度做總和)
print(result)
result=data.max(axis=0)
print(result)
result=data.mean(axis=1)
print(result)
print("----------")
result=data.cumsum()
print(result)
result=data.cumsum(axis=0) #針對欄做逐值累加(針對第一個維度做逐值累加)
print(result)

加法 [ 4  5 16]
乘法 [ 3  6 60]
大於 [ True False  True]
是否相等 [False False False]
----------
內積 [[-4 11  6]]
外積 [[ 2 -1  3 -2  4  1]
 [ 6 -3  9 -6 12  3]]
----------
總和 16
最大值 8
平均數 2.6666666666666665
標準差 4.268749491621899
----------
[-3  4 15]
[10  6]
[2 3 8]
[3.33333333 2.        ]
----------
[ 2  3 10  5  8 16]
[[ 2  1  7]
 [-3  4 15]]


In [23]:
#numpy.lesson4 多維陣列ndarray維度、形狀操作
#載入numpy套件
import numpy as np

#觀察資料形狀
data=np.ones(10)
print(data)
print(data.shape)
print("----------")

#資料轉置
data=np.array([
    [2, 4, 1],
    [1, 5, 0]
])
print(data.shape)
print(data.T.shape)
print(data.T)
print("----------")

#扁平化資料
data=np.array([
    [
        [2, 1, 3], [1, 2, 3]
    ],
    [
        [0, 2, 1], [8, 9, 10]
    ]
])
print(data.shape)
newData=data.ravel()
print(newData)
print(newData.shape)
print("----------")

#重塑資料形狀
data=np.array([
    [
        [2, 1, 3], [1, 2, 3]
    ],
    [
        [0, 2, 1], [8, 9, 10]
    ]
]) #2*2*3=12
newData=data.reshape(3, 4) #3*4=12
print(newData)
#newData=data.reshape(3, 5) #3*5=15錯誤 (因資料數量對不上)
print("----------")

data=np.zeros(12).reshape(2, 2, 3)
print(data)
print("----------")

data=np.arange(9).reshape(3, 3)
print(data)
print(data.T)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
(10,)
----------
(2, 3)
(3, 2)
[[2 1]
 [4 5]
 [1 0]]
----------
(2, 2, 3)
[ 2  1  3  1  2  3  0  2  1  8  9 10]
(12,)
----------
[[ 2  1  3  1]
 [ 2  3  0  2]
 [ 1  8  9 10]]
----------
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
----------
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [31]:
#numpy.lesson5 多維陣列ndarray索引、切片操作
#載入numpy套件
import numpy as np

#多維陣列的索引 Indexing
#單維度的資料
data=np.array([1, 5, 2, 10])
print(data[2])

#多維度資料
data=np.array([
    [0, 1],
    [10, -5],
    [2, 6]
])
print(data[0, 1])
print(data[1, 0])
print(data[2, 0])
print("----------")

#多維陣列的切片 Slicing
#單維度的切片
data=np.array([-1, -5, 2, 3])
print(data[0:3])
print(data[:2])
print(data[2:])
print(data[:])
print("----------")

#多維度的切片
data=np.array([
    [0, 1, 2], [3, 4, 5],
    [5, 4, 3], [2, 1, 0]
])
print(data[1:3, 0:2])
print(data[0:2, 1])
print("----------")

#使用...代表我全都要
data=np.array([
    [
        [8, 1, 3], 
        [-5, 5, 2]
    ],
    [
        [0, 1, 6],
        [4, 4, -3]
    ]
])
print(data[0, ...])
print(data[..., 1:3])

2
1
10
2
----------
[-1 -5  2]
[-1 -5]
[2 3]
[-1 -5  2  3]
----------
[[3 4]
 [5 4]]
[1 4]
----------
[[ 8  1  3]
 [-5  5  2]]
[[[ 1  3]
  [ 5  2]]

 [[ 1  6]
  [ 4 -3]]]


In [35]:
#numpy.lesson6 多維陣列ndarray合併操作
import numpy as np

#準備測試資料
arr1=np.array([
    [1, 2, 3],
    [4, 5, 6]
]) #2*3
arr2=np.array([
    [7, 8, 9],
    [10, 11, 12]
]) #2*3
arr3=np.array([
    [13, 14],
    [15, 16]
])
#合併第一個維度
result1=np.vstack((arr1, arr2)) #4*3
print(result1)
print("----------")

#合併第二個維度
result2=np.hstack((arr1, arr2)) #2*6
print(result2) 
print("----------")

result3=np.hstack((arr1, arr2, arr3))
print(result3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----------
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
----------
[[ 1  2  3  7  8  9 13 14]
 [ 4  5  6 10 11 12 15 16]]


In [40]:
#numpy.lesson7 多維陣列ndarray切割操作
import numpy as np

#準備測試資料
arr=np.array([
    [2, 4, 6, 8, 10, 12],
    [1, 3, 5, 4, 9, 11]
]) #2*6

#根據第一個維度切割
result1=np.vsplit(arr, 2)
print(result1)
print("----------")

#根據第二個維度切割
result2=np.hsplit(arr, 2)
print(result2)
print("----------")

#根據第二個維度切割成3個陣列
result3=np.hsplit(arr, 3)
print(result3)

[array([[ 2,  4,  6,  8, 10, 12]]), array([[ 1,  3,  5,  4,  9, 11]])]
----------
[array([[2, 4, 6],
       [1, 3, 5]]), array([[ 8, 10, 12],
       [ 4,  9, 11]])]
----------
[array([[2, 4],
       [1, 3]]), array([[6, 8],
       [5, 4]]), array([[10, 12],
       [ 9, 11]])]
